.PHONY: all experiments figures paper clean gate

# After `make all`, `make gate` checks paper numbers against regenerated results.
#
# Classical pipeline only. OEIS / LLM / ablation artefacts under results/ are
# never deleted by clean — they are not regenerated by `make all`.

all: experiments figures paper

experiments:
	python experiments/run_spectra.py
	python experiments/run_analysis.py
	python experiments/run_controls.py
	python experiments/run_deception.py

figures:
	python experiments/make_figures.py

paper:
	cd paper && pdflatex -interaction=nonstopmode main.tex
	cd paper && bibtex main
	cd paper && pdflatex -interaction=nonstopmode main.tex
	cd paper && pdflatex -interaction=nonstopmode main.tex

gate:
	python experiments/repro_gate.py

clean:
	python experiments/make_clean.py
